---
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  LambdaS3Bucket:
    Type: String
    Default: ''

Conditions:
  UsePublicBucket: !Equals
    - !Ref 'LambdaS3Bucket'
    - ''

Resources:
  OIDCProviderRefresher:
    Type: AWS::Lambda::Function
    Properties:
      Description: Refresh OIDC thumbprints
      FunctionName: aws-oidc-provider-refresher
      Code:
        S3Bucket: !If
          - UsePublicBucket
          - !Sub 'binxio-public-${AWS::Region}'
          - !Ref 'LambdaS3Bucket'
        S3Key: lambdas/aws-oidc-provider-refresher-0.0.0-3be90c8-dirty.zip
      Handler: aws_oidc_provider_refresher.command.handle
      Role: !GetAtt OIDCProviderRefresherRole.Arn
      Runtime: python3.9
      Timeout: 900

  OIDCProviderRefresherRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
      - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: UpdateOpenIDConnectProviderThumbprint
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - iam:UpdateOpenIDConnectProviderThumbprint
                  - iam:GetOpenIDConnectProvider
                  - tag:GetResources
                  - tag:GetTagKeys
                  - tag:GetTagValues
                Resource: "*"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole

  InvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !GetAtt OIDCProviderRefresher.Arn
      Principal: events.amazonaws.com

  Schedule:
    Type: AWS::Events::Rule
    Properties:
      Name: aws-cloudwatch-set-log-retention
      Description: set log retention on log streams
      ScheduleExpression: 'cron(58 * * * ? *)'
      State: ENABLED
      Targets:
        - Id: aws-oidc-provider-refresher
          Arn: !GetAtt OIDCProviderRefresher.Arn
          Input: >
            {"verbose": true, 
             "dry_run": false, 
             "max_thumbprints": 3, 
             "tags": ["auto-refresh=true"]
            }

